/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.calitos.ejer2;

import Excepciones.MiExcepcion;
import gestores.GestorDB;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import modelo.Articulo;
import utils.Utilidades;
import static utils.Utilidades.muestraErrorGrafico;

/**
 *
 * @author Carlos
 */
public class VentanaSesion extends javax.swing.JFrame {

    private static GestorDB miConexion;
    /**
     * Creates new form VentanaSesion
     * @param miConexion
     */
    public VentanaSesion(GestorDB miConexion) {
        this.miConexion = miConexion;
        initComponents();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiUsuario = new javax.swing.JLabel();
        textMensajePosible = new javax.swing.JLabel();
        textoContrasena = new javax.swing.JTextField();
        textoBBDD = new javax.swing.JTextField();
        etiContrasena = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        etiBBDD = new javax.swing.JLabel();
        botonSignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiUsuario.setText("Usuario");

        textMensajePosible.setText("mensajitos");

        textoBBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoBBDDActionPerformed(evt);
            }
        });

        etiContrasena.setText("Contraseña");

        etiBBDD.setText("Base de Datos");

        botonSignIn.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        botonSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textMensajePosible, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(botonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(etiBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(textoBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(etiUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(etiContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(textoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiBBDD)
                    .addComponent(textoBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiUsuario)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiContrasena)
                    .addComponent(textoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(textMensajePosible))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoBBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoBBDDActionPerformed
        try{
            estaLaBaseActiva(textoBBDD.getText());
            mensajitoCorrecto();
                    
        }catch(MiExcepcion ex){
            mensajito(ex);
        }
    }//GEN-LAST:event_textoBBDDActionPerformed

    private void botonSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSignInActionPerformed
        pideUsuario();
    }//GEN-LAST:event_botonSignInActionPerformed

    private void mensajito(MiExcepcion ex) {
        textMensajePosible.setText(ex.getMessage());
        textMensajePosible.setVisible(true);
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSignIn;
    private javax.swing.JLabel etiBBDD;
    private javax.swing.JLabel etiContrasena;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textMensajePosible;
    private javax.swing.JTextField textoBBDD;
    private javax.swing.JTextField textoContrasena;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables

    private void inicio() {
        textMensajePosible.setVisible(false);
        textMensajePosible.setForeground(Color.red);
        // load the image to a imageIcon:
        ImageIcon imageIcon = new ImageIcon("flecha.png"); 
        // transform it:
        Image image = imageIcon.getImage(); 
        Image newimg = image.getScaledInstance(80, 40, 
                java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        botonSignIn.setIcon(imageIcon); // NOI18N
        
    }
    private void pideUsuario() {
        miConexion = new GestorDB(textoUsuario.getText(), textoBBDD.getText(),
                "jdbc:mysql://127.0.0.1:3306/", textoContrasena.getText());
        //Si hay un conflicto con el puerto 3306, por XAMPP se puede entrar
        //a la configuración y cambiarlo a otro.
        try {
            
            miConexion.inicializarBBDD();
            
            
        } catch (MiExcepcion ex) {
            //Mensaje si el usuario es incorrecto: 
            switch (ex.getMessage().charAt(0)) {
                case 'U' -> {
                    //Usuario incorrecto:
                    mensajeUsuario();
                }
                default -> {
                    //BBDD apagada:
                    mensajeBaseApagada();
                    muestraErrorGrafico(ex.getMessage());
                }
            }

        } finally {
            try {
                miConexion.cerrarConexion();
            } catch (MiExcepcion ex) {
                Utilidades.muestraErrorGrafico(ex.getMessage());
            }
        }
        
    }

    private void abrirVentana() {
        //Si todo ha ido bien, la ventana se cierra (?)
        this.setVisible(false);
        Ejer2 ventanaNueva = new Ejer2(miConexion, this);
        ventanaNueva.setVisible(true);
        //No cerrar la conexión restará bastante. 
    }
    
    private void mensajeBaseApagada() {
        textMensajePosible.setVisible(true);
        textMensajePosible.setText("La Base de Datos está apagada...");
    }
    private void mensajeUsuario() {
        textMensajePosible.setVisible(true);
        textMensajePosible.setText("Usuario incorrecto...");
    }

    private boolean estaLaBaseActiva(String nombreTabla) throws MiExcepcion {
        boolean activa=false;
        miConexion = new GestorDB("a", nombreTabla,
                "jdbc:mysql://127.0.0.1:3306/", "a");
        miConexion.inicializarBBDD();
        if (miConexion.isMysqlEncendido()) {
            activa=true;
        }
        miConexion.cerrarConexion();
        return activa;
    }

    private void mensajitoCorrecto() {
        textMensajePosible.setForeground(Color.green);
        textMensajePosible.setText("¡Correcto!");
        textMensajePosible.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejer2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSesion(miConexion).setVisible(true);
            }
        });
    }

    void limpiar() {
        textMensajePosible.setText("");
        textoBBDD.setText("");
        textoContrasena.setText("");
        textoUsuario.setText("");
    }
}
